name: pre-merge-tests

on:
    pull_request: 
        types: ["opened", "reopened", "edited"]
    workflow_dispatch:

jobs:
    pull_request_tests:
        runs-on: ubuntu-latest

        steps:
            - name: Install Pester
              run: Install-Module -Name Pester -Force -SkipPublisherCheck

            - uses: actions/checkout@v4

            - name: bash debug
              shell: bash
              run: |
                pwd
                ls -la
                echo $GITHUB_HEAD_REF

            - name: Run tests
              shell: pwsh
              run: |
                cd $GITHUB_HEAD_REF
                Get-Location
                ls
                Invoke-Pester
