name: pre-merge-tests

on:
    pull_request: 
        types: ["opened", "reopened", "edited"]
    workflow_dispatch:

jobs:
    pull_request_tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: pwsh

        steps:
            - name: Install Pester
              run: Install-Module -Name Pester -Force -SkipPublisherCheck

            - uses: actions/checkout@v4

            - name: Run tests
              run: |
                cd $GITHUB_WORKSPACE
                cd $GITHUB_HEAD_REF
                Get-Location
                ls
                Invoke-Pester
