name: pre-merge-tests

on:
    pull_request: 
        types: [opened, reopened, edited, synchronize]

jobs:
    pull_request_tests:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        defaults:
          run:
            shell: pwsh
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Run tests
              shell: pwsh
              run: |
                cd ${env:GITHUB_HEAD_REF}
                Invoke-Pester