name: pre-merge-tests

on:
    pull_request: 
        types: ["opened", "reopened", "edited"]
    workflow_dispatch:

jobs:
    pull_request_tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: bash debug
              shell: bash
              run: |
                echo "Head ref: ${GITHUB_HEAD_REF}"

            - name: Run tests
              shell: pwsh
              run: |
                cd $GITHUB_HEAD_REF
                Invoke-Pester
