name: pre-merge-tests

on:
    pull_request: 
        types: [opened, reopened, edited, synchronize]
    workflow_dispatch:

jobs:
    pull_request_tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Run tests
              shell: pwsh
              run: |
                cd ${env:GITHUB_HEAD_REF}
                Invoke-Pester
